// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package tdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createWhiteboardStmt, err = db.PrepareContext(ctx, createWhiteboard); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWhiteboard: %w", err)
	}
	if q.deleteWhiteboardStmt, err = db.PrepareContext(ctx, deleteWhiteboard); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWhiteboard: %w", err)
	}
	if q.getWhiteboardStmt, err = db.PrepareContext(ctx, getWhiteboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetWhiteboard: %w", err)
	}
	if q.listWhiteboardStmt, err = db.PrepareContext(ctx, listWhiteboard); err != nil {
		return nil, fmt.Errorf("error preparing query ListWhiteboard: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createWhiteboardStmt != nil {
		if cerr := q.createWhiteboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWhiteboardStmt: %w", cerr)
		}
	}
	if q.deleteWhiteboardStmt != nil {
		if cerr := q.deleteWhiteboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWhiteboardStmt: %w", cerr)
		}
	}
	if q.getWhiteboardStmt != nil {
		if cerr := q.getWhiteboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWhiteboardStmt: %w", cerr)
		}
	}
	if q.listWhiteboardStmt != nil {
		if cerr := q.listWhiteboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWhiteboardStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	createWhiteboardStmt *sql.Stmt
	deleteWhiteboardStmt *sql.Stmt
	getWhiteboardStmt    *sql.Stmt
	listWhiteboardStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		createWhiteboardStmt: q.createWhiteboardStmt,
		deleteWhiteboardStmt: q.deleteWhiteboardStmt,
		getWhiteboardStmt:    q.getWhiteboardStmt,
		listWhiteboardStmt:   q.listWhiteboardStmt,
	}
}
