// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package tdb

import (
	"database/sql"
	"time"
)

type Authors struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Point struct {
	ID          int32           `json:"id"`
	StrokeID    sql.NullInt32   `json:"stroke_id"`
	XCoordinate sql.NullFloat64 `json:"x_coordinate"`
	YCoordinate sql.NullFloat64 `json:"y_coordinate"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Stroke struct {
	ID           int32          `json:"id"`
	WhiteboardID sql.NullInt32  `json:"whiteboard_id"`
	Color        sql.NullString `json:"color"`
	LineWidth    sql.NullInt32  `json:"line_width"`
	CreatedBy    sql.NullInt32  `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Whiteboard struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedBy sql.NullInt32  `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
